# Generated by Django 5.0.4 on 2024-04-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
